name: Publish to TestApp.io
on:
  push:
    branches:
      - main

jobs:
  export_android:

    runs-on: ubuntu-latest

    steps:

      - run: echo "Starting the workflow"
        name: Checkout repository
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build release
        run: ./gradlew assembleRelease

      - name: Publish APK to TestApp.io
        uses: testappio/github-action@v5
        with:
          api_token: ${{secrets.TESTAPPIO_API_TOKEN}}
          app_id: ${{secrets.TESTAPPIO_APP_ID}}
          file: app/build/outputs/apk/release/app-release-unsigned.apk
          release_notes: "Testing manual release notes..."
          git_release_notes: true
          include_git_commit_id: false
          notify: true